
package frame;

import Hamming.Archivos;
import Hamming.DesprotegerArchivo;
import static frame.ProtegerFrame.tamano;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class DesprotegerFrame extends javax.swing.JFrame {


     public static Archivos archivo= new DesprotegerArchivo();
        public static File ar;
        public static File arD;
     
     
    public DesprotegerFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.ButtonGroup();
        despues = new java.awt.TextArea();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        desprotegerB = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boton_no = new javax.swing.JRadioButton();
        boton_si = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        ruta_antes = new javax.swing.JTextField();
        ruta_despues = new javax.swing.JTextField();
        jSantes = new javax.swing.JScrollPane();
        ANTES = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        DESPUES = new javax.swing.JTextArea();
        estadisticas = new javax.swing.JButton();
        aux0 = new javax.swing.JPanel();
        tituloHamming = new javax.swing.JLabel();
        exitB = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();
        fondo4 = new javax.swing.JLabel();
        fondo0 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        despues.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(562, 972));

        background.setBackground(new java.awt.Color(28, 40, 61));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 26, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jPanel2.setBackground(new java.awt.Color(18, 26, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(28, 40, 61));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/key.png"))); // NOI18N

        desprotegerB.setBackground(new java.awt.Color(18, 26, 51));
        desprotegerB.setFont(new java.awt.Font("Roboto Cn", 0, 22)); // NOI18N
        desprotegerB.setForeground(new java.awt.Color(255, 255, 255));
        desprotegerB.setText("DESPROTEGER");
        desprotegerB.setBorder(null);
        desprotegerB.setMaximumSize(new java.awt.Dimension(336, 36));
        desprotegerB.setMinimumSize(new java.awt.Dimension(336, 36));
        desprotegerB.setPreferredSize(new java.awt.Dimension(336, 36));
        desprotegerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desprotegerBMouseClicked(evt);
            }
        });
        desprotegerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desprotegerBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desprotegerB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desprotegerB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 190, 210));

        jPanel6.setBackground(new java.awt.Color(28, 40, 61));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 183, 246));
        jLabel2.setText("CORREGIR:");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(700, 10, 140, 20);

        Grupo.add(boton_no);
        boton_no.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        boton_no.setForeground(new java.awt.Color(255, 255, 255));
        boton_no.setText("NO");
        boton_no.setEnabled(false);
        jPanel6.add(boton_no);
        boton_no.setBounds(890, 10, 50, 27);

        Grupo.add(boton_si);
        boton_si.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        boton_si.setForeground(new java.awt.Color(255, 255, 255));
        boton_si.setText("SI");
        boton_si.setEnabled(false);
        jPanel6.add(boton_si);
        boton_si.setBounds(850, 10, 40, 27);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jButton2.setText("Seleccionar archivo (.HAx, .HEx)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(10, 10, 350, 30);

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 50));

        ruta_antes.setEditable(false);
        ruta_antes.setBackground(new java.awt.Color(0, 0, 0));
        ruta_antes.setForeground(new java.awt.Color(43, 183, 246));
        ruta_antes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta_antesActionPerformed(evt);
            }
        });
        jPanel2.add(ruta_antes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 30));

        ruta_despues.setEditable(false);
        ruta_despues.setBackground(new java.awt.Color(0, 0, 0));
        ruta_despues.setForeground(new java.awt.Color(43, 183, 246));
        jPanel2.add(ruta_despues, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 350, 30));

        ANTES.setEditable(false);
        ANTES.setBackground(new java.awt.Color(255, 255, 255));
        ANTES.setColumns(20);
        ANTES.setLineWrap(true);
        ANTES.setRows(5);
        ANTES.setWrapStyleWord(true);
        jSantes.setViewportView(ANTES);

        jPanel2.add(jSantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, 290));

        DESPUES.setEditable(false);
        DESPUES.setBackground(new java.awt.Color(255, 255, 255));
        DESPUES.setColumns(20);
        DESPUES.setLineWrap(true);
        DESPUES.setRows(5);
        DESPUES.setWrapStyleWord(true);
        jScrollPane1.setViewportView(DESPUES);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 350, 290));

        estadisticas.setBackground(new java.awt.Color(18, 26, 51));
        estadisticas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        estadisticas.setForeground(new java.awt.Color(43, 183, 246));
        estadisticas.setText("VER ESTADÍSTICAS");
        estadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 183, 246)));
        estadisticas.setEnabled(false);
        estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasActionPerformed(evt);
            }
        });
        jPanel2.add(estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 190, 30));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1030, 410));

        aux0.setBackground(new java.awt.Color(0, 0, 0));

        tituloHamming.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        tituloHamming.setForeground(new java.awt.Color(218, 236, 255));
        tituloHamming.setText("DESPROTEGER ARCHIVO");
        tituloHamming.setToolTipText("");

        javax.swing.GroupLayout aux0Layout = new javax.swing.GroupLayout(aux0);
        aux0.setLayout(aux0Layout);
        aux0Layout.setHorizontalGroup(
            aux0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamming, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        aux0Layout.setVerticalGroup(
            aux0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamming, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        background.add(aux0, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 600, 50));

        exitB.setBackground(new java.awt.Color(18, 26, 51));
        exitB.setFont(new java.awt.Font("Roboto Slab", 0, 16)); // NOI18N
        exitB.setForeground(new java.awt.Color(255, 255, 255));
        exitB.setText("SALIR");
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });
        background.add(exitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 90, 30));

        volver.setBackground(new java.awt.Color(18, 26, 51));
        volver.setFont(new java.awt.Font("Roboto Slab", 0, 15)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        background.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 650, 320));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo3.setText("jLabel6");
        background.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 600, 80));

        fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo4.setText("jLabel6");
        background.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 580, 70));

        fondo0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo0.setText("jLabel6");
        background.add(fondo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 580, 70));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo1.setText("jLabel6");
        background.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 20, 580, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        MainHamm m = new MainHamm();
        this.dispose();
        m.setVisible(true);

    }//GEN-LAST:event_volverMouseClicked

    private void desprotegerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desprotegerBActionPerformed
        // TODO add your handling code here:
        if(ruta_antes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un archivo","Error", JOptionPane.ERROR_MESSAGE);
            
        }else if(archivo.controlExtensionHE() && (!boton_si.isSelected() && !boton_no.isSelected())){
            JOptionPane.showMessageDialog(null,"Debe seleccionar si desea corregir el archivo","Error", JOptionPane.ERROR_MESSAGE);    
        }else{
            
             try {
                
                boolean corregir=false;
                if(boton_si.isSelected()){
                    corregir=true;
                }
                int bloque=0;
                int info=0;
                int controles=0;
                String nuevaRuta;
                ar = archivo.archivoSeleccionado;
                String ext = archivo.getExtension();
                String ruta =  ar.getAbsolutePath();
                String nuevaExtension="";
                
                if(ext.equals("HA1") || (ext.equals("HE1") && !corregir) ){
                    bloque=4;
                    info=26;
                    controles=6;
                    nuevaExtension=".DE1";
                }else if(ext.equals("HA2") || (ext.equals("HE2") && !corregir) ){
                    bloque=256;
                    info= 2036;
                    controles=12;
                    nuevaExtension=".DE2";
                }else if(ext.equals("HA3") || (ext.equals("HE3") && !corregir)  ){
                    bloque= 8192;
                    info=65519;
                    controles=17;
                    nuevaExtension=".DE3";
                }
             
                if(ext.equals("HE1") && corregir){
                    bloque=4;
                    info=26;
                    controles=6;
                    nuevaExtension=".DC1";
                }else if(ext.equals("HE2") && corregir ){
                    bloque=256;
                    info= 2036;
                    controles=12;
                    nuevaExtension=".DC2";
                }else if(ext.equals("HE3") && corregir ){
                    bloque= 8192;
                    info=65519;
                    controles=17;
                    nuevaExtension=".DC3";
                }
                
                //Lee el archivo, lo decodifica y lo guarda en la nueva ruta con la nueva extension
                arD = archivo.desprotegido(archivo.decodeHA(archivo.leerArchivo(ruta),bloque,info,controles,corregir),ruta,nuevaExtension);
           
                if(archivo.getDobleError() && corregir){
                    JOptionPane.showMessageDialog(null, "El archivo no se pudo corregir ya que contiene doble error", "Lo sentimos", JOptionPane.ERROR_MESSAGE);
                }
                FileReader fr= new FileReader(arD);
                BufferedReader br = new BufferedReader(fr);
                String texto="";
                String linea="";
                while(((linea=br.readLine())!=null)){
                    texto+=linea+"\n";
                }
                
                ruta_despues.setText(arD.getAbsolutePath());
                DESPUES.setText(texto);
                estadisticas.setEnabled(true);
            
             } catch (IOException ex) {
                 Logger.getLogger(DesprotegerFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
            
        }
    }//GEN-LAST:event_desprotegerBActionPerformed

    private void desprotegerBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desprotegerBMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_desprotegerBMouseClicked

    private void ruta_antesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta_antesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruta_antesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        archivo.archivoSeleccionado = null;
         File ar = archivo.SelectArchivo();
         String ext= archivo.getExtension();
         archivo.resetDobleError();
            if(archivo.archivoSeleccionado != null){
                   if(archivo.controlExtensionHE()){ 
             boton_si.setEnabled(true);
             boton_no.setEnabled(true);
            }
         
            ruta_antes.setText(ar.getAbsolutePath()); //escribe la ruta del archivo
           
            ANTES.setText(archivo.readFile());
            
            
            }
      
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasActionPerformed
        // TODO add your handling code here:
        String errores = "";
        if(boton_si.isSelected()){
            errores="Si";
        }else{
            errores = "No";
        }

       JOptionPane.showMessageDialog(null, "\n"
            + "- Tamaño del archivo original: " + tamano(ar) + " Bytes\n"
            + "- Tamaño del archivo Desprotegido: " + tamano(arD) + " Bytes\n"
            + "- Corrección de errores: " + errores 
            ,"ETADÍSTICAS OBTENIDAS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_estadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesprotegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesprotegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesprotegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesprotegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesprotegerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ANTES;
    private javax.swing.JTextArea DESPUES;
    private javax.swing.ButtonGroup Grupo;
    private javax.swing.JPanel aux0;
    private javax.swing.JPanel background;
    private javax.swing.JRadioButton boton_no;
    private javax.swing.JRadioButton boton_si;
    private javax.swing.JButton desprotegerB;
    private java.awt.TextArea despues;
    private javax.swing.JButton estadisticas;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel fondo0;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jSantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ruta_antes;
    private javax.swing.JTextField ruta_despues;
    private javax.swing.JLabel tituloHamming;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
