/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import frame.DescFrame;
import frame.CompactFrame;

/**
 *
 * @author Usuario
 */
public class MainHuff extends javax.swing.JFrame {

    /**
     * Creates new form mainHuff
     */
    public MainHuff() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        CompactB = new javax.swing.JButton();
        DescB = new javax.swing.JButton();
        extension1 = new javax.swing.JLabel();
        extension2 = new javax.swing.JLabel();
        imageL3 = new javax.swing.JLabel();
        imageL2 = new javax.swing.JLabel();
        tituloHuffman = new javax.swing.JLabel();
        aux0 = new javax.swing.JPanel();
        exitB = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();
        fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(28, 40, 61));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 26, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jPanel2.setBackground(new java.awt.Color(18, 26, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(28, 40, 61));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CompactB.setBackground(new java.awt.Color(18, 26, 51));
        CompactB.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        CompactB.setForeground(new java.awt.Color(43, 183, 246));
        CompactB.setText("COMPACTAR UN ARCHIVO");
        CompactB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CompactB.setMaximumSize(new java.awt.Dimension(336, 36));
        CompactB.setMinimumSize(new java.awt.Dimension(336, 36));
        CompactB.setPreferredSize(new java.awt.Dimension(336, 36));
        CompactB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompactBMouseClicked(evt);
            }
        });
        CompactB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompactBActionPerformed(evt);
            }
        });

        DescB.setBackground(new java.awt.Color(18, 26, 51));
        DescB.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        DescB.setForeground(new java.awt.Color(43, 183, 246));
        DescB.setText("DESCOMPACTAR UN ARCHIVO");
        DescB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DescB.setMaximumSize(new java.awt.Dimension(336, 36));
        DescB.setMinimumSize(new java.awt.Dimension(336, 36));
        DescB.setPreferredSize(new java.awt.Dimension(336, 36));
        DescB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescBMouseClicked(evt);
            }
        });
        DescB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescBActionPerformed(evt);
            }
        });

        extension1.setBackground(new java.awt.Color(51, 51, 51));
        extension1.setForeground(new java.awt.Color(102, 102, 102));
        extension1.setText(".txt .docx");

        extension2.setBackground(new java.awt.Color(153, 153, 153));
        extension2.setForeground(new java.awt.Color(102, 102, 102));
        extension2.setText(".huf");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(extension1)
                            .addComponent(extension2)
                            .addComponent(CompactB, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(DescB, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(CompactB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extension1)
                .addGap(42, 42, 42)
                .addComponent(DescB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extension2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 460, 300));

        imageL3.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\zip.png"));
        jPanel2.add(imageL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 350, 370));

        imageL2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\cir"
            + ".png"));
    jPanel2.add(imageL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 480, 410));

    background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1030, 410));

    tituloHuffman.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
    tituloHuffman.setForeground(new java.awt.Color(218, 236, 255));
    tituloHuffman.setText("HUFFMAN CODE");
    tituloHuffman.setToolTipText("");
    background.add(tituloHuffman, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 440, 50));

    aux0.setBackground(new java.awt.Color(0, 0, 0));

    javax.swing.GroupLayout aux0Layout = new javax.swing.GroupLayout(aux0);
    aux0.setLayout(aux0Layout);
    aux0Layout.setHorizontalGroup(
        aux0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 390, Short.MAX_VALUE)
    );
    aux0Layout.setVerticalGroup(
        aux0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 50, Short.MAX_VALUE)
    );

    background.add(aux0, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 390, 50));

    exitB.setBackground(new java.awt.Color(18, 26, 51));
    exitB.setFont(new java.awt.Font("Roboto Slab", 0, 16)); // NOI18N
    exitB.setForeground(new java.awt.Color(255, 255, 255));
    exitB.setText("SALIR");
    exitB.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitBActionPerformed(evt);
        }
    });
    background.add(exitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 90, 30));

    volver.setBackground(new java.awt.Color(18, 26, 51));
    volver.setFont(new java.awt.Font("Roboto Slab", 0, 15)); // NOI18N
    volver.setForeground(new java.awt.Color(255, 255, 255));
    volver.setText("VOLVER");
    volver.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            volverMouseClicked(evt);
        }
    });
    volver.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            volverActionPerformed(evt);
        }
    });
    background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

    fondo1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\a.gif"));
    fondo1.setText("jLabel6");
    background.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 500, 580, 80));

    fondo2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\a.gif"));
    fondo2.setText("jLabel6");
    background.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 20, 580, 80));

    fondo3.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\a.gif"));
    fondo3.setText("jLabel6");
    background.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 580, 80));

    fondo4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\images\\a.gif"));
    background.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 580, 80));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompactBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompactBMouseClicked
       
    }//GEN-LAST:event_CompactBMouseClicked

    private void CompactBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompactBActionPerformed
        CompactFrame c = new CompactFrame();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CompactBActionPerformed

    private void DescBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescBMouseClicked
        // TODO add your handling code here:
       DescFrame c = new DescFrame();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DescBMouseClicked

    private void DescBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescBActionPerformed

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        mainMenu m = new mainMenu(); //crea ventana principal
        this.dispose(); //cierra la ventana actual
        m.setVisible(true);//hace visible la nueva ventana
    }//GEN-LAST:event_volverMouseClicked

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHuff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompactB;
    private javax.swing.JButton DescB;
    private javax.swing.JPanel aux0;
    private javax.swing.JPanel background;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel extension1;
    private javax.swing.JLabel extension2;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JLabel imageL2;
    private javax.swing.JLabel imageL3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel tituloHuffman;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
