
package frame;


import Hamming.Archivos;
import Hamming.ProtegerArchivo;
import Hamming.ProtegerHamming;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ProtegerFrame extends javax.swing.JFrame {
    
        public static Archivos archivo= new ProtegerArchivo();
        public static File ar;
        public static File arD;
    


    /**
     * Creates new form proteger
     */
    public ProtegerFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        //rsscalelabel.RSScaleLabel.setScaleLabel(jLabel3,"src/images/key.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Errores = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modulos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NoE = new javax.swing.JRadioButton();
        SiE2 = new javax.swing.JRadioButton();
        SiE1 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        protegerB = new javax.swing.JButton();
        ruta_antes = new javax.swing.JTextField();
        ruta_despues = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ANTES = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        DESPUES = new javax.swing.JTextArea();
        estadisticas = new javax.swing.JButton();
        aux0 = new javax.swing.JPanel();
        tituloHamming = new javax.swing.JLabel();
        exitB = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();
        fondo4 = new javax.swing.JLabel();
        fondo0 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(28, 40, 61));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 26, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jPanel2.setBackground(new java.awt.Color(18, 26, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(28, 40, 61));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 183, 246));
        jLabel1.setText("MODULO:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(700, 10, 120, 30);

        modulos.setBackground(new java.awt.Color(204, 204, 204));
        modulos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        modulos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32", "2048", "65536" }));
        modulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosActionPerformed(evt);
            }
        });
        jPanel3.add(modulos);
        modulos.setBounds(820, 10, 120, 30);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jButton1.setText("Seleccionar archivo (.txt)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(10, 10, 350, 30);

        jLabel2.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 183, 246));
        jLabel2.setText("ERRORES:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(370, 10, 130, 32);

        Errores.add(NoE);
        NoE.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NoE.setForeground(new java.awt.Color(43, 183, 246));
        NoE.setText("NO");
        NoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoEActionPerformed(evt);
            }
        });
        jPanel3.add(NoE);
        NoE.setBounds(640, 10, 50, 26);

        Errores.add(SiE2);
        SiE2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        SiE2.setForeground(new java.awt.Color(43, 183, 246));
        SiE2.setText("SI(2)");
        SiE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiE2ActionPerformed(evt);
            }
        });
        jPanel3.add(SiE2);
        SiE2.setBounds(570, 10, 70, 26);

        Errores.add(SiE1);
        SiE1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        SiE1.setForeground(new java.awt.Color(43, 183, 246));
        SiE1.setText("SI (1)");
        SiE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiE1ActionPerformed(evt);
            }
        });
        jPanel3.add(SiE1);
        SiE1.setBounds(500, 10, 70, 26);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 50));

        jPanel5.setBackground(new java.awt.Color(28, 40, 61));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/key.png"))); // NOI18N

        protegerB.setBackground(new java.awt.Color(18, 26, 51));
        protegerB.setFont(new java.awt.Font("Roboto Cn", 0, 22)); // NOI18N
        protegerB.setForeground(new java.awt.Color(255, 255, 255));
        protegerB.setText("PROTEGER");
        protegerB.setBorder(null);
        protegerB.setMaximumSize(new java.awt.Dimension(336, 36));
        protegerB.setMinimumSize(new java.awt.Dimension(336, 36));
        protegerB.setPreferredSize(new java.awt.Dimension(336, 36));
        protegerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                protegerBMouseClicked(evt);
            }
        });
        protegerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protegerBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protegerB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(protegerB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 190, 210));

        ruta_antes.setEditable(false);
        ruta_antes.setBackground(new java.awt.Color(0, 0, 0));
        ruta_antes.setForeground(new java.awt.Color(43, 183, 246));
        ruta_antes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta_antesActionPerformed(evt);
            }
        });
        jPanel2.add(ruta_antes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 30));

        ruta_despues.setEditable(false);
        ruta_despues.setBackground(new java.awt.Color(0, 0, 0));
        ruta_despues.setForeground(new java.awt.Color(43, 183, 246));
        ruta_despues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta_despuesActionPerformed(evt);
            }
        });
        jPanel2.add(ruta_despues, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 350, 30));

        ANTES.setEditable(false);
        ANTES.setBackground(new java.awt.Color(255, 255, 255));
        ANTES.setColumns(20);
        ANTES.setLineWrap(true);
        ANTES.setRows(5);
        ANTES.setToolTipText("");
        ANTES.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ANTES);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, 290));

        DESPUES.setEditable(false);
        DESPUES.setBackground(new java.awt.Color(255, 255, 255));
        DESPUES.setColumns(20);
        DESPUES.setLineWrap(true);
        DESPUES.setRows(5);
        DESPUES.setWrapStyleWord(true);
        jScrollPane2.setViewportView(DESPUES);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 350, 290));

        estadisticas.setBackground(new java.awt.Color(18, 26, 51));
        estadisticas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        estadisticas.setForeground(new java.awt.Color(43, 183, 246));
        estadisticas.setText("VER ESTADÍSTICAS");
        estadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 183, 246)));
        estadisticas.setEnabled(false);
        estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasActionPerformed(evt);
            }
        });
        jPanel2.add(estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 361, 190, 30));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1030, 410));

        aux0.setBackground(new java.awt.Color(0, 0, 0));
        aux0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloHamming.setFont(new java.awt.Font("Roboto", 1, 52)); // NOI18N
        tituloHamming.setForeground(new java.awt.Color(218, 236, 255));
        tituloHamming.setText("PROTEGER ARCHIVO");
        tituloHamming.setToolTipText("");
        aux0.add(tituloHamming, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        background.add(aux0, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 500, 50));

        exitB.setBackground(new java.awt.Color(18, 26, 51));
        exitB.setFont(new java.awt.Font("Roboto Slab", 0, 16)); // NOI18N
        exitB.setForeground(new java.awt.Color(255, 255, 255));
        exitB.setText("SALIR");
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });
        background.add(exitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 90, 30));

        volver.setBackground(new java.awt.Color(18, 26, 51));
        volver.setFont(new java.awt.Font("Roboto Slab", 0, 15)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo2.setText("jLabel6");
        background.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 650, 320));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo3.setText("jLabel6");
        background.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 600, 80));

        fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo4.setText("jLabel6");
        background.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 580, 70));

        fondo0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo0.setText("jLabel6");
        background.add(fondo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 580, 70));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.gif"))); // NOI18N
        fondo1.setText("jLabel6");
        background.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 20, 580, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBActionPerformed

    private void modulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modulosActionPerformed

    private void protegerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protegerBActionPerformed
        // TODO add your handling code here:
        
        if(ruta_antes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un archivo","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }if(!SiE2.isSelected() && !NoE.isSelected() && !SiE1.isSelected()){
            JOptionPane.showMessageDialog(null,"Debe seleccionar con o sin errores","Error", JOptionPane.ERROR_MESSAGE);    
        }else{
            
             try {
                String nuevaRuta;
                ar = archivo.archivoSeleccionado;
                String ext = archivo.getExtension();
                String ruta =  ar.getAbsolutePath();
                
                
                //Lee el archivo, lo decodifica y lo guarda en la nueva ruta con la nueva extension
                int errores;
                if(SiE1.isSelected()){
                    errores=1;
                }else if(SiE2.isSelected()){
                    errores=2;
                }else{
                    errores=0;
                }
                String bloque= String.valueOf(modulos.getSelectedItem());
                int hamming = Integer.parseInt(bloque);
                arD = ProtegerHamming.protegerArchivo(hamming, ruta,errores);
           
                
                FileReader fr= new FileReader(arD);
                BufferedReader br = new BufferedReader(fr);
                String texto="";
                String linea="";
                while(((linea=br.readLine())!=null)){
                    texto+=linea+"\n";
                }
                DESPUES.setText(texto); //muestra el texto del archivo
                ruta_despues.setText(arD.getAbsolutePath());
                estadisticas.setEnabled(true);
            
            
             } catch (IOException ex) {
                 Logger.getLogger(DesprotegerFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
            
        }
        
    }//GEN-LAST:event_protegerBActionPerformed

    private void protegerBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protegerBMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_protegerBMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        MainHamm m = new MainHamm(); //crea ventana principal
        this.dispose(); //cierra la ventana actual
        m.setVisible(true);//hace visible la nueva ventana
        
        
    }//GEN-LAST:event_volverMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        archivo.archivoSeleccionado = null;
        File ar = archivo.SelectArchivo();
        
        if(archivo.archivoSeleccionado != null){
             ruta_antes.setText(ar.getAbsolutePath()); //escribe la ruta del archivo
        
        
        
         try{
            FileReader fr= new FileReader(ar);
            BufferedReader br = new BufferedReader(fr);
            String texto="";
            String linea="";
            while(((linea=br.readLine())!=null)){
                texto+=linea+"\n";
            }
            ANTES.setText(texto); //muestra el texto del archivo
            
        }catch(Exception e){
            
        }
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ruta_antesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta_antesActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_ruta_antesActionPerformed

    private void ruta_despuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta_despuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruta_despuesActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    private void NoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoEActionPerformed

    private void SiE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiE2ActionPerformed

    private void SiE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiE1ActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasActionPerformed
        // TODO add your handling code here:
        String bloque= String.valueOf(modulos.getSelectedItem());
        int bitsControl=archivo.getCantBitsControl(bloque);
        int bitsInfo= archivo.getCantBitsInfo(bloque);
        long cantModulos = archivo.getCantModulos(bloque, arD);
        
        JOptionPane.showMessageDialog(null, "\n"
            + "- Bloque de Hamming: " + bloque+" Bits\n"
            + "- Tamaño del archivo original: " + tamano(ar) + " Bytes\n"
            + "- Tamaño del archivo protegido: " + tamano(arD) + " Bytes\n"
            + "- Cantidad de bits de control por módulo (+ bit de paridad): " + bitsControl+"\n"
            + "- Cantidad de bits de información por módulo: " + bitsInfo+"\n"
            + "- Cantidad de módulos para este archivo: " + cantModulos+"\n"
            + "- Cantidad total de bits de control: " + (bitsControl * cantModulos)+"\n"
            + "- Cantidad total de bits de información: " + (bitsInfo * cantModulos)
                
            ,"ETADÍSTICAS OBTENIDAS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_estadisticasActionPerformed

    public static long tamano(File archivo) {
        try {
            return Files.size(Paths.get(archivo.getAbsolutePath()));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return -1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProtegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProtegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProtegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProtegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ProtegerFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ANTES;
    private javax.swing.JTextArea DESPUES;
    private javax.swing.ButtonGroup Errores;
    private javax.swing.JRadioButton NoE;
    private javax.swing.JRadioButton SiE1;
    private javax.swing.JRadioButton SiE2;
    private javax.swing.JPanel aux0;
    private javax.swing.JPanel background;
    private javax.swing.JButton estadisticas;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel fondo0;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JLabel fondo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> modulos;
    private javax.swing.JButton protegerB;
    private javax.swing.JTextField ruta_antes;
    private javax.swing.JTextField ruta_despues;
    private javax.swing.JLabel tituloHamming;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    private String obtenerExtension(String ruta) {
       String extension = "";
       int indice = ruta.lastIndexOf(".");
       if(indice>0 && indice < ruta.length() -1){
           extension= ruta.substring(indice+1);
       }
       return extension;
    }
}
